# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - dogtor-ai

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    #permissions:
      #contents: read #This is required for actions/checkout

    steps:
      - name: Checkout Source
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      
      - name: Install Dependecies
        run: npm install

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dogtor-web-ai'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
          